/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  AddressLike,
  BaseContract,
  BigNumberish,
  BytesLike,
  ContractMethod,
  ContractRunner,
  EventFragment,
  FunctionFragment,
  Interface,
  Listener,
  Result
} from "ethers";
import type {
  TypedContractEvent,
  TypedContractMethod,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedLogDescription
} from "../common";

export declare namespace TokenRelayer {
  export type ExecuteParamsStruct = {
    token: AddressLike;
    owner: AddressLike;
    value: BigNumberish;
    deadline: BigNumberish;
    permitV: BigNumberish;
    permitR: BytesLike;
    permitS: BytesLike;
    payloadData: BytesLike;
    payloadValue: BigNumberish;
    payloadNonce: BigNumberish;
    payloadDeadline: BigNumberish;
    payloadV: BigNumberish;
    payloadR: BytesLike;
    payloadS: BytesLike;
  };

  export type ExecuteParamsStructOutput = [
    token: string,
    owner: string,
    value: bigint,
    deadline: bigint,
    permitV: bigint,
    permitR: string,
    permitS: string,
    payloadData: string,
    payloadValue: bigint,
    payloadNonce: bigint,
    payloadDeadline: bigint,
    payloadV: bigint,
    payloadR: string,
    payloadS: string
  ] & {
    token: string;
    owner: string;
    value: bigint;
    deadline: bigint;
    permitV: bigint;
    permitR: string;
    permitS: string;
    payloadData: string;
    payloadValue: bigint;
    payloadNonce: bigint;
    payloadDeadline: bigint;
    payloadV: bigint;
    payloadR: string;
    payloadS: string;
  };
}

export interface TokenRelayerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deployer"
      | "destinationContract"
      | "execute"
      | "executedCalls"
      | "isExecutionCompleted"
      | "tokenApproved"
      | "usedPayloadNonces"
      | "withdrawToken"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "RelayerExecuted"): EventFragment;

  encodeFunctionData(functionFragment: "deployer", values?: undefined): string;
  encodeFunctionData(functionFragment: "destinationContract", values?: undefined): string;
  encodeFunctionData(functionFragment: "execute", values: [TokenRelayer.ExecuteParamsStruct]): string;
  encodeFunctionData(functionFragment: "executedCalls", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "isExecutionCompleted", values: [AddressLike, BigNumberish]): string;
  encodeFunctionData(functionFragment: "tokenApproved", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "usedPayloadNonces", values: [AddressLike, BigNumberish]): string;
  encodeFunctionData(functionFragment: "withdrawToken", values: [AddressLike, BigNumberish]): string;

  decodeFunctionResult(functionFragment: "deployer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "destinationContract", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "executedCalls", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isExecutionCompleted", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenApproved", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usedPayloadNonces", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdrawToken", data: BytesLike): Result;
}

export namespace RelayerExecutedEvent {
  export type InputTuple = [signer: AddressLike, token: AddressLike, amount: BigNumberish];
  export type OutputTuple = [signer: string, token: string, amount: bigint];
  export interface OutputObject {
    signer: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TokenRelayer extends BaseContract {
  connect(runner?: ContractRunner | null): TokenRelayer;
  waitForDeployment(): Promise<this>;

  interface: TokenRelayerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(event: TCEvent): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>;

  deployer: TypedContractMethod<[], [string], "view">;

  destinationContract: TypedContractMethod<[], [string], "view">;

  execute: TypedContractMethod<[params: TokenRelayer.ExecuteParamsStruct], [boolean], "payable">;

  executedCalls: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  isExecutionCompleted: TypedContractMethod<[signer: AddressLike, nonce: BigNumberish], [boolean], "view">;

  tokenApproved: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  usedPayloadNonces: TypedContractMethod<[arg0: AddressLike, arg1: BigNumberish], [boolean], "view">;

  withdrawToken: TypedContractMethod<[token: AddressLike, amount: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

  getFunction(nameOrSignature: "deployer"): TypedContractMethod<[], [string], "view">;
  getFunction(nameOrSignature: "destinationContract"): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<[params: TokenRelayer.ExecuteParamsStruct], [boolean], "payable">;
  getFunction(nameOrSignature: "executedCalls"): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isExecutionCompleted"
  ): TypedContractMethod<[signer: AddressLike, nonce: BigNumberish], [boolean], "view">;
  getFunction(nameOrSignature: "tokenApproved"): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "usedPayloadNonces"
  ): TypedContractMethod<[arg0: AddressLike, arg1: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "withdrawToken"
  ): TypedContractMethod<[token: AddressLike, amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "RelayerExecuted"
  ): TypedContractEvent<RelayerExecutedEvent.InputTuple, RelayerExecutedEvent.OutputTuple, RelayerExecutedEvent.OutputObject>;

  filters: {
    "RelayerExecuted(address,address,uint256)": TypedContractEvent<
      RelayerExecutedEvent.InputTuple,
      RelayerExecutedEvent.OutputTuple,
      RelayerExecutedEvent.OutputObject
    >;
    RelayerExecuted: TypedContractEvent<
      RelayerExecutedEvent.InputTuple,
      RelayerExecutedEvent.OutputTuple,
      RelayerExecutedEvent.OutputObject
    >;
  };
}
