const EURC_VAULT_ACCOUNT_ID = '6bsD97dS8ZyomMmp1DLCnCtx25oABtf19dypQKdZe6FBQXSm';
const MIN_WITHDRAWAL_AMOUNT = '10000000000000';
const HORIZON_URL = 'https://horizon.stellar.org';
//const HORIZON_URL = 'https://horizon-testnet.stellar.org';
const BASE_FEE = '1000000';

const ASSET_CODE = 'EURC';
const ASSET_ISSUER = 'GAQRF3UGHBT6JYQZ7YSUYCIYWAF4T2SAA5237Q5LIQYJOHHFAWDXZ7NM';

//Testnet asset values
//const ASSET_CODE = 'USDC';
//const ASSET_ISSUER = 'GAKNDFRRWA3RPWNLTI3G4EBSD3RGNZZOY5WKWYMQ6CQTG3KIEKPYWAYC';

module.exports = { ASSET_ISSUER, ASSET_CODE, BASE_FEE, HORIZON_URL, MIN_WITHDRAWAL_AMOUNT, EURC_VAULT_ACCOUNT_ID };
