/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../common";
import type {
  MockRelayerDestination,
  MockRelayerDestinationInterface,
} from "../../../contracts/mocks/MockRelayerDestination";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
    ],
    name: "SafeERC20FailedOperation",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "pull",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "refund",
        type: "uint256",
      },
    ],
    name: "pullAndRefund",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600e575f5ffd5b5061028f8061001c5f395ff3fe608060405260043610610028575f3560e01c80636822beba1461002c5780637372c2b514610041575b5f5ffd5b61003f61003a3660046101e0565b610060565b005b34801561004c575f5ffd5b5061003f61005b36600461021f565b6100fc565b61006b84848461010c565b6040515f90339083908381818185875af1925050503d805f81146100aa576040519150601f19603f3d011682016040523d82523d5f602084013e6100af565b606091505b50509050806100f55760405162461bcd60e51b815260206004820152600d60248201526c1c99599d5b990819985a5b1959609a1b60448201526064015b60405180910390fd5b5050505050565b61010783838361010c565b505050565b6101076001600160a01b03841633848461012a848484846001610158565b61015257604051635274afe760e01b81526001600160a01b03851660048201526024016100ec565b50505050565b6040516323b872dd60e01b5f8181526001600160a01b038781166004528616602452604485905291602083606481808c5af1925060015f511483166101b45783831516156101a8573d5f823e3d81fd5b5f883b113d1516831692505b604052505f60605295945050505050565b80356001600160a01b03811681146101db575f5ffd5b919050565b5f5f5f5f608085870312156101f3575f5ffd5b6101fc856101c5565b935061020a602086016101c5565b93969395505050506040820135916060013590565b5f5f5f60608486031215610231575f5ffd5b61023a846101c5565b9250610248602085016101c5565b92959294505050604091909101359056fea26469706673582212203472ade4b8db4d4e4eccd0c9b66238df3b11fc6813c1e453cb84ba3dfffaf92c64736f6c634300081c0033";

type MockRelayerDestinationConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockRelayerDestinationConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockRelayerDestination__factory extends ContractFactory {
  constructor(...args: MockRelayerDestinationConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockRelayerDestination & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(
    runner: ContractRunner | null
  ): MockRelayerDestination__factory {
    return super.connect(runner) as MockRelayerDestination__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockRelayerDestinationInterface {
    return new Interface(_abi) as MockRelayerDestinationInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockRelayerDestination {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as MockRelayerDestination;
  }
}
