/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockERC20Permit } from "./MockERC20Permit";
export type { MockRelayerDestination } from "./MockRelayerDestination";
