import { Address, getAddress, Hex, keccak256, PublicClient, parseAbi, parseAbiItem, parseEventLogs } from "viem";

/**
 * Shared chain-reading core for generate-manifest.ts / verify-manifest.ts.
 *
 * R01 (docs/architecture-monerium-b2b-onramp.md §5): the manifest produced from
 * this state is CONSISTENCY EVIDENCE, NOT A TRUST ROOT. It is generated by Vortex from
 * the same chain state it attests to, so it cannot prove the deployment was honest —
 * only that the deployment has not silently changed since the manifest was published.
 * Independent verification of WHAT the contracts do requires reading the verified
 * source on a block explorer.
 */

export const MANIFEST_VERSION = 4;

export const MANIFEST_PURPOSE =
  "Consistency evidence for a VortexForwarder deployment (Monerium B2B onramp). " +
  "NOT a trust root (re-review R01): this file is produced by Vortex from the same chain state it attests to, " +
  "so it proves only that the deployment has not silently changed since publication — not that it was honest. " +
  "Verify contract behavior independently against the verified source on a block explorer.";

// ------------------------------------------------------------------ ABI surface
// Mirrors contracts/monerium-forwarder/src/VortexForwarder.sol + VortexForwarderFactory.sol.

export const factoryAbi = parseAbi([
  "function implementation() view returns (address)",
  "function MIN_SWAP_FLOOR() view returns (uint256)",
  "function CAP_CEILING() view returns (uint256)",
  "function guardian() view returns (address)",
  "function globalPaused() view returns (bool)",
  "function minSwapAmount() view returns (uint256)",
  "function perSwapCap() view returns (uint256)",
  "function isForwarder(address forwarder) view returns (bool)",
  "function subsidyVault() view returns (address)",
  "function routeCount() view returns (uint256)",
  "function route(uint256 index) view returns (bytes path, bool enabled)"
]);

export const forwarderDeployedEvent = parseAbiItem(
  "event ForwarderDeployed(address indexed forwarder, address indexed destination, uint32 targetPpm, uint32 floorPpm, bytes32 salt)"
);

export const forwarderConfigAbi = parseAbi([
  "function destination() view returns (address)",
  "function targetPpm() view returns (uint32)",
  "function floorPpm() view returns (uint32)"
]);

export const implementationAbi = parseAbi([
  "function EURE() view returns (address)",
  "function EURC() view returns (address)",
  "function USDC() view returns (address)",
  "function ROUTER() view returns (address)",
  "function ORACLE() view returns (address)",
  "function ORACLE_DECIMALS() view returns (uint8)",
  "function FACTORY() view returns (address)",
  "function ATTESTOR() view returns (address)",
  "function FEE_RECIPIENT() view returns (address)",
  "function RECOVERY_WALLET() view returns (address)",
  "function MAX_ORACLE_AGE() view returns (uint256)",
  "function SLIPPAGE_BPS() view returns (uint16)",
  "function MAX_FEE_PPM() view returns (uint32)",
  "function MAX_REFERENCE_DEVIATION_BPS() view returns (uint16)",
  "function RECOVERY_DELAY() view returns (uint256)",
  "function TRIGGER_DELAY() view returns (uint256)",
  "function LINK_HASH_191() view returns (bytes32)",
  "function RECOVERY_HASH() view returns (bytes32)",
  "function LINK_MESSAGE() view returns (string)"
]);

// ------------------------------------------------------------------ manifest shape

/** Implementation-level immutables shared by all clones (plan §2.1). */
export interface ImplementationImmutables {
  ATTESTOR: string;
  EURC: string;
  EURE: string;
  FACTORY: string;
  FEE_RECIPIENT: string;
  LINK_HASH_191: Hex;
  LINK_MESSAGE: string;
  MAX_FEE_PPM: number;
  MAX_ORACLE_AGE: string;
  MAX_REFERENCE_DEVIATION_BPS: number;
  ORACLE: string;
  ORACLE_DECIMALS: number;
  RECOVERY_DELAY: string;
  RECOVERY_HASH: Hex;
  RECOVERY_WALLET: string;
  ROUTER: string;
  SLIPPAGE_BPS: number;
  TRIGGER_DELAY: string;
  USDC: string;
}

export interface ForwarderManifestEntry {
  address: string;
  deploy: {
    blockNumber: string;
    salt: Hex;
    txHash: Hex;
  };
  /** Guardian-adjustable under the contract's bounded, timelocked fee policy (ppm below the reference). */
  guardianMutable: {
    floorPpm: number;
    targetPpm: number;
  };
  /**
   * Fixed for the lifetime of the clone: the destination has no setter (a client wallet
   * change means a new clone, runbook §5) and factory registration never changes.
   * Mismatch = incident.
   */
  immutables: {
    destination: string;
    isForwarder: boolean;
  };
  /** keccak256 of the clone's runtime code; must equal the EIP-1167 code for `implementation.address`. */
  runtimeBytecodeHash: Hex;
}

export interface CoreState {
  chainId: number;
  factory: {
    address: string;
    immutables: {
      CAP_CEILING: string;
      MIN_SWAP_FLOOR: string;
      implementation: string;
    };
    /**
     * Guardian-tunable within the immutable bounds (registry P6/P7) plus role/pause
     * state, the subsidy vault and the on-chain validated route whitelist. Drift here
     * is legitimate operation: the verifier reports NOTICE, not failure.
     */
    operational: {
      globalPaused: boolean;
      guardian: string;
      minSwapAmount: string;
      perSwapCap: string;
      routes: { enabled: boolean; path: Hex }[];
      subsidyVault: string;
    };
    runtimeBytecodeHash: Hex;
  };
  implementation: {
    address: string;
    immutables: ImplementationImmutables;
    runtimeBytecodeHash: Hex;
  };
}

export interface Manifest extends CoreState {
  forwarders: ForwarderManifestEntry[];
  generatedAt: string;
  manifestVersion: number;
  purpose: string;
}

// ------------------------------------------------------------------ helpers

/** Runtime code of a standard EIP-1167 minimal proxy pointing at `implementation`. */
export function eip1167RuntimeCode(implementation: Address): Hex {
  return `0x363d3d373d3d3d363d73${implementation.slice(2).toLowerCase()}5af43d82803e903d91602b57fd5bf3` as Hex;
}

async function codeHash(client: PublicClient, address: Address): Promise<Hex> {
  const code = await client.getCode({ address });
  if (!code || code === "0x") {
    throw new Error(`no contract code at ${address}`);
  }
  return keccak256(code);
}

function read<T>(
  client: PublicClient,
  abi: typeof factoryAbi | typeof implementationAbi | typeof forwarderConfigAbi,
  address: Address,
  functionName: string,
  args: unknown[] = []
): Promise<T> {
  // biome-ignore lint/suspicious/noExplicitAny: generic dispatcher over three hand-pinned ABIs
  return client.readContract({ abi, address, args, functionName } as any) as Promise<T>;
}

// ------------------------------------------------------------------ deploy provenance

export interface DeployProvenance {
  blockNumber: bigint;
  salt: Hex;
  txHash: Hex;
}

const LOG_CHUNK = 50_000n;

/**
 * Finds the factory's deploy block by binary search over getCode (needs an archive
 * RPC); falls back to 0 when historical getCode is unavailable.
 */
async function findDeployBlock(client: PublicClient, factory: Address, latest: bigint): Promise<bigint> {
  try {
    let lo = 0n;
    let hi = latest;
    while (lo < hi) {
      const mid = (lo + hi) / 2n;
      const code = await client.getCode({ address: factory, blockNumber: mid });
      if (code && code !== "0x") {
        hi = mid;
      } else {
        lo = mid + 1n;
      }
    }
    return lo;
  } catch {
    return 0n;
  }
}

/**
 * Enumerates all forwarders ever deployed by the factory from its ForwarderDeployed
 * events, oldest first. Needs an RPC that serves historical eth_getLogs (many free
 * endpoints gate this behind archive plans — pass a logs-capable RPC to the scripts
 * via --logs-rpc in that case).
 */
export async function enumerateForwarders(
  client: PublicClient,
  factoryAddress: Address
): Promise<{ deploy: DeployProvenance; forwarder: Address }[]> {
  const factory = getAddress(factoryAddress);
  const latest = await client.getBlockNumber();
  // biome-ignore lint/suspicious/noExplicitAny: viem log generics collapse across the two getLogs call shapes below
  let rawLogs: any[];
  try {
    // Single full-range query first — cheap when the provider allows it.
    rawLogs = await client.getLogs({ address: factory, event: forwarderDeployedEvent, fromBlock: 0n, toBlock: latest });
  } catch {
    const start = await findDeployBlock(client, factory, latest);
    rawLogs = [];
    for (let from = start; from <= latest; from += LOG_CHUNK) {
      const to = from + LOG_CHUNK - 1n > latest ? latest : from + LOG_CHUNK - 1n;
      rawLogs.push(
        ...(await client.getLogs({ address: factory, event: forwarderDeployedEvent, fromBlock: from, toBlock: to }))
      );
    }
  }
  return rawLogs
    .filter(log => log.blockNumber !== null && log.transactionHash !== null)
    .map(log => ({
      deploy: {
        blockNumber: log.blockNumber as bigint,
        salt: log.args.salt as Hex,
        txHash: log.transactionHash as Hex
      },
      forwarder: getAddress(log.args.forwarder as Address)
    }));
}

/**
 * Re-derives a forwarder's deploy provenance from its deploy transaction receipt: the
 * receipt must be successful and contain the factory's ForwarderDeployed event for the
 * forwarder. Works on any full node (receipts by hash are not archive-gated), which is
 * what lets third parties verify provenance through free public RPCs.
 */
export async function resolveDeployProvenance(
  client: PublicClient,
  factoryAddress: Address,
  forwarderAddress: Address,
  txHash: Hex
): Promise<DeployProvenance> {
  const receipt = await client.getTransactionReceipt({ hash: txHash });
  if (receipt.status !== "success") {
    throw new Error(`deploy tx ${txHash} did not succeed`);
  }
  const events = parseEventLogs({ abi: [forwarderDeployedEvent], logs: receipt.logs }).filter(
    log =>
      log.address.toLowerCase() === factoryAddress.toLowerCase() &&
      (log.args.forwarder as Address).toLowerCase() === forwarderAddress.toLowerCase()
  );
  if (events.length === 0) {
    throw new Error(`deploy tx ${txHash} contains no ForwarderDeployed event for ${forwarderAddress} from ${factoryAddress}`);
  }
  return { blockNumber: receipt.blockNumber, salt: events[0].args.salt as Hex, txHash };
}

// ------------------------------------------------------------------ state readers

/** Reads chainId + factory + implementation sections from live chain state. */
export async function readCoreState(client: PublicClient, factoryAddress: Address): Promise<CoreState> {
  const factory = getAddress(factoryAddress);
  const chainId = await client.getChainId();

  const [
    implementation,
    minSwapFloor,
    capCeiling,
    guardian,
    globalPaused,
    minSwapAmount,
    perSwapCap,
    subsidyVault,
    routeCount
  ] = await Promise.all([
    read<Address>(client, factoryAbi, factory, "implementation"),
    read<bigint>(client, factoryAbi, factory, "MIN_SWAP_FLOOR"),
    read<bigint>(client, factoryAbi, factory, "CAP_CEILING"),
    read<Address>(client, factoryAbi, factory, "guardian"),
    read<boolean>(client, factoryAbi, factory, "globalPaused"),
    read<bigint>(client, factoryAbi, factory, "minSwapAmount"),
    read<bigint>(client, factoryAbi, factory, "perSwapCap"),
    read<Address>(client, factoryAbi, factory, "subsidyVault"),
    read<bigint>(client, factoryAbi, factory, "routeCount")
  ]);
  const routes = await Promise.all(
    Array.from({ length: Number(routeCount) }, (_, index) =>
      read<[Hex, boolean]>(client, factoryAbi, factory, "route", [BigInt(index)]).then(([path, enabled]) => ({
        enabled,
        path
      }))
    )
  );

  const [
    eure,
    eurc,
    usdc,
    router,
    oracle,
    oracleDecimals,
    implFactory,
    attestor,
    feeRecipient,
    maxOracleAge,
    slippageBps,
    maxFeePpm,
    maxReferenceDeviationBps,
    recoveryWallet,
    recoveryDelay,
    triggerDelay,
    linkHash191,
    recoveryHash,
    linkMessage
  ] = await Promise.all([
    read<Address>(client, implementationAbi, implementation, "EURE"),
    read<Address>(client, implementationAbi, implementation, "EURC"),
    read<Address>(client, implementationAbi, implementation, "USDC"),
    read<Address>(client, implementationAbi, implementation, "ROUTER"),
    read<Address>(client, implementationAbi, implementation, "ORACLE"),
    read<number>(client, implementationAbi, implementation, "ORACLE_DECIMALS"),
    read<Address>(client, implementationAbi, implementation, "FACTORY"),
    read<Address>(client, implementationAbi, implementation, "ATTESTOR"),
    read<Address>(client, implementationAbi, implementation, "FEE_RECIPIENT"),
    read<bigint>(client, implementationAbi, implementation, "MAX_ORACLE_AGE"),
    read<number>(client, implementationAbi, implementation, "SLIPPAGE_BPS"),
    read<number>(client, implementationAbi, implementation, "MAX_FEE_PPM"),
    read<number>(client, implementationAbi, implementation, "MAX_REFERENCE_DEVIATION_BPS"),
    read<Address>(client, implementationAbi, implementation, "RECOVERY_WALLET"),
    read<bigint>(client, implementationAbi, implementation, "RECOVERY_DELAY"),
    read<bigint>(client, implementationAbi, implementation, "TRIGGER_DELAY"),
    read<Hex>(client, implementationAbi, implementation, "LINK_HASH_191"),
    read<Hex>(client, implementationAbi, implementation, "RECOVERY_HASH"),
    read<string>(client, implementationAbi, implementation, "LINK_MESSAGE")
  ]);

  return {
    chainId,
    factory: {
      address: factory,
      immutables: {
        CAP_CEILING: capCeiling.toString(),
        implementation: getAddress(implementation),
        MIN_SWAP_FLOOR: minSwapFloor.toString()
      },
      operational: {
        globalPaused,
        guardian: getAddress(guardian),
        minSwapAmount: minSwapAmount.toString(),
        perSwapCap: perSwapCap.toString(),
        routes,
        subsidyVault: subsidyVault === "0x0000000000000000000000000000000000000000" ? subsidyVault : getAddress(subsidyVault)
      },
      runtimeBytecodeHash: await codeHash(client, factory)
    },
    implementation: {
      address: getAddress(implementation),
      immutables: {
        ATTESTOR: getAddress(attestor),
        EURC: getAddress(eurc),
        EURE: getAddress(eure),
        FACTORY: getAddress(implFactory),
        FEE_RECIPIENT: getAddress(feeRecipient),
        LINK_HASH_191: linkHash191,
        LINK_MESSAGE: linkMessage,
        MAX_FEE_PPM: Number(maxFeePpm),
        MAX_ORACLE_AGE: maxOracleAge.toString(),
        MAX_REFERENCE_DEVIATION_BPS: Number(maxReferenceDeviationBps),
        ORACLE: getAddress(oracle),
        ORACLE_DECIMALS: Number(oracleDecimals),
        RECOVERY_DELAY: recoveryDelay.toString(),
        RECOVERY_HASH: recoveryHash,
        RECOVERY_WALLET: getAddress(recoveryWallet),
        ROUTER: getAddress(router),
        SLIPPAGE_BPS: Number(slippageBps),
        TRIGGER_DELAY: triggerDelay.toString(),
        USDC: getAddress(usdc)
      },
      runtimeBytecodeHash: await codeHash(client, implementation)
    }
  };
}

/** Reads one forwarder's live per-clone config + code hash into a manifest entry. */
export async function readForwarderEntry(
  client: PublicClient,
  factoryAddress: Address,
  forwarderAddress: Address,
  deploy: DeployProvenance
): Promise<ForwarderManifestEntry> {
  const factory = getAddress(factoryAddress);
  const forwarder = getAddress(forwarderAddress);
  const [destination, targetPpm, floorPpm, isForwarder, forwarderCodeHash] = await Promise.all([
    read<Address>(client, forwarderConfigAbi, forwarder, "destination"),
    read<number>(client, forwarderConfigAbi, forwarder, "targetPpm"),
    read<number>(client, forwarderConfigAbi, forwarder, "floorPpm"),
    read<boolean>(client, factoryAbi, factory, "isForwarder", [forwarder]),
    codeHash(client, forwarder)
  ]);
  return {
    address: forwarder,
    deploy: {
      blockNumber: deploy.blockNumber.toString(),
      salt: deploy.salt,
      txHash: deploy.txHash
    },
    guardianMutable: {
      floorPpm: Number(floorPpm),
      targetPpm: Number(targetPpm)
    },
    immutables: {
      destination: getAddress(destination),
      isForwarder
    },
    runtimeBytecodeHash: forwarderCodeHash
  };
}
