/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppApiKeysRouteImport } from './routes/_app/api-keys'
import { Route as AppLimitsRouteImport } from './routes/_app/limits'
import { Route as AppOverviewRouteImport } from './routes/_app/overview'
import { Route as AppQuoteRouteImport } from './routes/_app/quote'
import { Route as AppRecipientsRouteImport } from './routes/_app/recipients'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTransactionsRouteImport } from './routes/_app/transactions'
import { Route as AppTransferRouteImport } from './routes/_app/transfer'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as MoneriumCallbackRouteImport } from './routes/monerium.callback'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppApiKeysRoute = AppApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AppRoute,
} as any)
const AppLimitsRoute = AppLimitsRouteImport.update({
  id: '/limits',
  path: '/limits',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)
const AppQuoteRoute = AppQuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipientsRoute = AppRecipientsRouteImport.update({
  id: '/recipients',
  path: '/recipients',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppTransferRoute = AppTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => AppRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const MoneriumCallbackRoute = MoneriumCallbackRouteImport.update({
  id: '/monerium/callback',
  path: '/monerium/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api-keys': typeof AppApiKeysRoute
  '/limits': typeof AppLimitsRoute
  '/overview': typeof AppOverviewRoute
  '/quote': typeof AppQuoteRoute
  '/recipients': typeof AppRecipientsRoute
  '/settings': typeof AppSettingsRoute
  '/transactions': typeof AppTransactionsRoute
  '/transfer': typeof AppTransferRoute
  '/invite/$token': typeof InviteTokenRoute
  '/monerium/callback': typeof MoneriumCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/api-keys': typeof AppApiKeysRoute
  '/limits': typeof AppLimitsRoute
  '/overview': typeof AppOverviewRoute
  '/quote': typeof AppQuoteRoute
  '/recipients': typeof AppRecipientsRoute
  '/settings': typeof AppSettingsRoute
  '/transactions': typeof AppTransactionsRoute
  '/transfer': typeof AppTransferRoute
  '/invite/$token': typeof InviteTokenRoute
  '/monerium/callback': typeof MoneriumCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/api-keys': typeof AppApiKeysRoute
  '/_app/limits': typeof AppLimitsRoute
  '/_app/overview': typeof AppOverviewRoute
  '/_app/quote': typeof AppQuoteRoute
  '/_app/recipients': typeof AppRecipientsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/transactions': typeof AppTransactionsRoute
  '/_app/transfer': typeof AppTransferRoute
  '/invite/$token': typeof InviteTokenRoute
  '/monerium/callback': typeof MoneriumCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/api-keys'
    | '/limits'
    | '/overview'
    | '/quote'
    | '/recipients'
    | '/settings'
    | '/transactions'
    | '/transfer'
    | '/invite/$token'
    | '/monerium/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/api-keys'
    | '/limits'
    | '/overview'
    | '/quote'
    | '/recipients'
    | '/settings'
    | '/transactions'
    | '/transfer'
    | '/invite/$token'
    | '/monerium/callback'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/api-keys'
    | '/_app/limits'
    | '/_app/overview'
    | '/_app/quote'
    | '/_app/recipients'
    | '/_app/settings'
    | '/_app/transactions'
    | '/_app/transfer'
    | '/invite/$token'
    | '/monerium/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  InviteTokenRoute: typeof InviteTokenRoute
  MoneriumCallbackRoute: typeof MoneriumCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/api-keys': {
      id: '/_app/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof AppApiKeysRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/limits': {
      id: '/_app/limits'
      path: '/limits'
      fullPath: '/limits'
      preLoaderRoute: typeof AppLimitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quote': {
      id: '/_app/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof AppQuoteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipients': {
      id: '/_app/recipients'
      path: '/recipients'
      fullPath: '/recipients'
      preLoaderRoute: typeof AppRecipientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transfer': {
      id: '/_app/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof AppTransferRouteImport
      parentRoute: typeof AppRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monerium/callback': {
      id: '/monerium/callback'
      path: '/monerium/callback'
      fullPath: '/monerium/callback'
      preLoaderRoute: typeof MoneriumCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppApiKeysRoute: typeof AppApiKeysRoute
  AppLimitsRoute: typeof AppLimitsRoute
  AppOverviewRoute: typeof AppOverviewRoute
  AppQuoteRoute: typeof AppQuoteRoute
  AppRecipientsRoute: typeof AppRecipientsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppTransferRoute: typeof AppTransferRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppApiKeysRoute: AppApiKeysRoute,
  AppLimitsRoute: AppLimitsRoute,
  AppOverviewRoute: AppOverviewRoute,
  AppQuoteRoute: AppQuoteRoute,
  AppRecipientsRoute: AppRecipientsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppTransferRoute: AppTransferRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  InviteTokenRoute: InviteTokenRoute,
  MoneriumCallbackRoute: MoneriumCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
