/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTransferRouteImport } from './routes/_app/transfer'
import { Route as AppTransactionsRouteImport } from './routes/_app/transactions'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppRecipientsRouteImport } from './routes/_app/recipients'
import { Route as AppOverviewRouteImport } from './routes/_app/overview'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransferRoute = AppTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => AppRoute,
} as any)
const AppTransactionsRoute = AppTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipientsRoute = AppRecipientsRouteImport.update({
  id: '/recipients',
  path: '/recipients',
  getParentRoute: () => AppRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/overview': typeof AppOverviewRoute
  '/recipients': typeof AppRecipientsRoute
  '/settings': typeof AppSettingsRoute
  '/transactions': typeof AppTransactionsRoute
  '/transfer': typeof AppTransferRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/overview': typeof AppOverviewRoute
  '/recipients': typeof AppRecipientsRoute
  '/settings': typeof AppSettingsRoute
  '/transactions': typeof AppTransactionsRoute
  '/transfer': typeof AppTransferRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/overview': typeof AppOverviewRoute
  '/_app/recipients': typeof AppRecipientsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/transactions': typeof AppTransactionsRoute
  '/_app/transfer': typeof AppTransferRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/overview'
    | '/recipients'
    | '/settings'
    | '/transactions'
    | '/transfer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/overview'
    | '/recipients'
    | '/settings'
    | '/transactions'
    | '/transfer'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/overview'
    | '/_app/recipients'
    | '/_app/settings'
    | '/_app/transactions'
    | '/_app/transfer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/transfer': {
      id: '/_app/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof AppTransferRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/transactions': {
      id: '/_app/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AppTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recipients': {
      id: '/_app/recipients'
      path: '/recipients'
      fullPath: '/recipients'
      preLoaderRoute: typeof AppRecipientsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/overview': {
      id: '/_app/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppOverviewRoute: typeof AppOverviewRoute
  AppRecipientsRoute: typeof AppRecipientsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTransactionsRoute: typeof AppTransactionsRoute
  AppTransferRoute: typeof AppTransferRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppOverviewRoute: AppOverviewRoute,
  AppRecipientsRoute: AppRecipientsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTransactionsRoute: AppTransactionsRoute,
  AppTransferRoute: AppTransferRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
