import { GoogleSpreadsheet, GoogleSpreadsheetWorksheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';

interface GoogleCredentials {
  email: string;
  key: string;
}

const SCOPES = ['https://www.googleapis.com/auth/spreadsheets'];

export async function initGoogleSpreadsheet(sheetId: string, googleCredentials: GoogleCredentials) {
  // Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
  if (!googleCredentials.email || !googleCredentials.key) {
    throw new Error('Missing some google credentials');
  }

  const serviceAccountAuth = new JWT({
    // env var values here are copied from service account credentials generated by google
    // see "Authentication" section in docs for more info
    email: googleCredentials.email,
    key: googleCredentials.key,
    scopes: SCOPES,
  });

  const doc = new GoogleSpreadsheet(sheetId, serviceAccountAuth);
  try {
    await doc.loadInfo();
  } catch (error) {
    console.error(`Error loading Google Spreadsheet ${sheetId}:`, error);
    throw error;
  }

  return doc;
}

export async function getOrCreateSheet(doc: GoogleSpreadsheet, headerValues: string[]) {
  let sheet = doc.sheetsByIndex[0];
  try {
    await sheet.loadHeaderRow();
    const sheetHeaders = sheet.headerValues;

    // Compare the header values to the expected header values
    if (
      sheetHeaders.length !== headerValues.length &&
      sheetHeaders.every((value, index) => value === headerValues[index])
    ) {
      // Create a new sheet if the headers don't match
      console.log('Creating new sheet');
      sheet = await doc.addSheet({ headerValues });
    }
  } catch (error) {
    // Assume the error is due to the sheet not having any rows
    await sheet.setHeaderRow(headerValues);
  }

  return sheet;
}

export async function appendData(sheet: GoogleSpreadsheetWorksheet, data: Record<string, string>) {
  await sheet.addRow(data);
}
